### ISSUE TITLE
Cool but useless without a colors.json example

### ISSUE THREAD

**Issue by moiseslodeiro** [fredmny/dotfiles#1]
Please, provide a color.json (.cache/wal/ folder) for testing and customization purposes ;-)

**Comment by fredmny** [comment]
Hey @moiseslodeiro, I added the file. It matches the first screenshot. 

In case it interests you, I use a shortcut (bw) to set the wallpaper and restart qtile with the new scheme within ranger, which can be seen in the [rc.conf](https://github.com/fredmny/dotfiles/blob/master/.config/ranger/rc.conf) file.

Sorry for not answering sooner. Still learning and getting used to git and github
